/**
 * Real places a guest can go today, beside the 1849 story of each town.
 *
 * Research: ~/Documents/BOBR/research/volcano_local/VOLCANO_LOCAL_PLACES_20260923.md
 * (spoke report + hub re-fetch of the theatre, St. George and Sizemore pages).
 * Hours rot: every entry carries verifiedAt and its source, and the card says
 * when it was checked. Coordinates are stored only where OpenStreetMap placed
 * the building; Main St addresses are interpolation and stay without a pin.
 */

export type LocalPlaceKind = 'food' | 'show' | 'explore'

export interface LocalPlace {
  id: string
  townId: string
  name: string
  kind: LocalPlaceKind
  address: string
  phone?: string
  url: string
  /** What a guest finds now. */
  today: string
  /** What stood here in the Gold Rush, dated. */
  then: string
  /** ISO date the hours/status were last read from `source`. */
  verifiedAt: string
  source: string
  coordinates?: { lat: number; lng: number }
}

export interface LocalAvoid {
  id: string
  townId: string
  name: string
  reason: string
  verifiedAt: string
}

export const LOCAL_PLACES: LocalPlace[] = [
  {
    id: 'vol_sizemore',
    townId: 'volcano',
    name: 'Sizemore Country Store & Restaurant',
    kind: 'food',
    address: '16146 Main St, Volcano',
    phone: '209-296-4459',
    url: 'https://www.sizemorecountrystore.com/',
    today: 'Open daily 10–7 (kitchen to 6:30): burgers, deli, BBQ, baked goods, Amador beer and local wine, garden patio.',
    then: 'Claims 1852 — two brick-and-limestone stores (Mandelbaum & Klauber’s “Sacramento” and Burleson’s), joined in 1861.',
    verifiedAt: '2026-09-23',
    source: 'https://www.sizemorecountrystore.com/',
  },
  {
    id: 'vol_baked_in_amador',
    townId: 'volcano',
    name: 'BAKED. In Amador',
    kind: 'food',
    address: '16154 Main St, Volcano',
    phone: '209-296-4301',
    url: 'https://bakedinamador.com/',
    today: 'Sourdough bakery: bread, sourdough pastry, soup and made-to-order plates. Fri–Sun 8–3, closed Mon–Thu.',
    then: 'In 1853 Volcano already had three bakeries; this one keeps the habit on Main Street.',
    verifiedAt: '2026-09-23',
    source: 'https://bakedinamador.com/',
  },
  {
    id: 'vol_union_pub',
    townId: 'volcano',
    name: 'Volcano Union Pub',
    kind: 'food',
    address: '21375 Consolation St, Volcano',
    phone: '209-296-7711',
    url: 'https://www.volcanounion.com/',
    today: 'Pub Fri 4:30–8, Sat–Sun 12–8, Mon 4:30–8; closed Tue–Thu. The inn’s rooms are closed for 2026.',
    then: 'Built in 1880 as a miners’ boarding house.',
    verifiedAt: '2026-09-23',
    source: 'https://www.volcanounion.com/',
    coordinates: { lat: 38.4431, lng: -120.63079 },
  },
  {
    id: 'vol_cobblestone',
    townId: 'volcano',
    name: 'Cobblestone Theatre (Volcano Theatre Co.)',
    kind: 'show',
    address: 'Main St just north of National St, Volcano (company address 16121 Main)',
    url: 'https://volcanotheatre.net/tickets/',
    today: '45 open seats. 2026: Dr. Jekyll and Mr. Hyde to Oct 3; On The Farce Day of Christmas Nov 6–Dec 13. $24 / $22 seniors, online only.',
    then: 'Stone walls of 1856 — Adolph Mayer’s Tobacco and Cigar Emporium, later Lavezzo’s Wine Shop; gutted by fire in 1900.',
    verifiedAt: '2026-09-23',
    source: 'https://volcanotheatre.net/about/',
  },
  {
    id: 'vol_amphitheatre',
    townId: 'volcano',
    name: 'Volcano Amphitheatre',
    kind: 'show',
    address: 'Main St, across from the Cobblestone, Volcano',
    url: 'https://volcanotheatre.net/tickets/',
    today: 'The summer stage (June–August), entered through an old stone storefront.',
    then: 'The restored Gold Rush facade of the Hale Sash and Door Company.',
    verifiedAt: '2026-09-23',
    source: 'https://volcanotheatre.net/about/',
  },
  {
    id: 'vol_old_abe',
    townId: 'volcano',
    name: 'Old Abe cannon',
    kind: 'explore',
    address: 'At the Main St / Consolation St junction, across from the Union Inn, Volcano',
    url: 'https://westernmininghistory.com/gallery-image/36956/',
    today: 'Free, outdoors, any time.',
    then: 'Bronze six-pounder cast in 1837 by Cyrus Alger & Co.; legend says it came to town in a hearse around 1863.',
    verifiedAt: '2026-09-23',
    source: 'https://westernmininghistory.com/gallery-image/36956/',
  },
  {
    id: 'vol_soldiers_park',
    townId: 'volcano',
    name: 'Soldiers Gulch plaques (Soldiers Memorial Park)',
    kind: 'explore',
    address: 'Off Main St, Volcano',
    url: 'https://commons.wikimedia.org/wiki/File:Plaque_commemorating_founding_of_Volcano_California.jpg',
    today: 'Two plaques on the founding; a short walk from the hotel.',
    then: 'Stevenson’s New York regiment men camped and mined here from late 1848; the first wagon party came in 1849.',
    verifiedAt: '2026-09-23',
    source: 'https://npgallery.nps.gov/NRHP/GetAsset/NRHP/84000757_text',
    coordinates: { lat: 38.44241, lng: -120.6316 },
  },
  {
    id: 'vol_black_chasm',
    townId: 'volcano',
    name: 'Black Chasm Cavern',
    kind: 'explore',
    address: '15701 Pioneer Volcano Rd, Volcano',
    phone: '888-488-1960',
    url: 'https://cavetouring.com/contact-hours-black-chasm',
    today: 'Guided walking tours, weekdays 10–4, weekends 10–5 (hours can change — check first).',
    then: 'Found by miners in the 1850s.',
    verifiedAt: '2026-09-23',
    source: 'https://cavetouring.com/contact-hours-black-chasm',
  },
  {
    id: 'vol_chawse',
    townId: 'volcano',
    name: 'Indian Grinding Rock State Historic Park (Chaw’se)',
    kind: 'explore',
    address: '14881 Pine Grove-Volcano Rd, Pine Grove',
    url: 'https://www.parks.ca.gov/?page_id=553',
    today: 'Sunrise to sunset, museum 10–4, $8 per vehicle.',
    then: 'Northern Sierra Miwok homeland: about 1,185 bedrock mortars, ground for acorn meal for centuries before 1849.',
    verifiedAt: '2026-09-23',
    source: 'https://www.parks.ca.gov/?page_id=553',
  },
  {
    id: 'wp_willows',
    townId: 'west_point',
    name: 'Willow’s on Main',
    kind: 'food',
    address: '311 Main St, West Point',
    phone: '209-293-9266',
    url: 'https://www.gocalaveras.com/business/restaurants/willows-on-main/',
    today: 'Breakfast and lunch café — coffee, espresso, mimosas. Hours differ between listings; call ahead.',
    then: 'No 1850s building recorded here.',
    verifiedAt: '2026-09-23',
    source: 'https://www.restaurantji.com/ca/west-point/willows-on-main-/',
  },
  {
    id: 'wp_pizza_plus',
    townId: 'west_point',
    name: 'Pizza Plus',
    kind: 'food',
    address: '429 Main St, West Point',
    phone: '209-293-7779',
    url: 'https://www.restaurantji.com/ca/west-point/pizza-plus-/',
    today: 'Pizza, daily 11–8 (listing updated Aug 2026).',
    then: 'No 1850s building recorded here.',
    verifiedAt: '2026-09-23',
    source: 'https://www.restaurantji.com/ca/west-point/pizza-plus-/',
  },
  {
    id: 'wp_tacos_marcos',
    townId: 'west_point',
    name: 'Tacos Estilo Marcos',
    kind: 'food',
    address: '344 Main St, West Point',
    phone: '209-660-9508',
    url: 'https://www.restaurantji.com/ca/west-point/tacos-estilo-marcos-/',
    today: 'Tacos, Mon–Fri 9–7, Sat 9–6, closed Sunday (listing updated Aug 2026).',
    then: 'No 1850s building recorded here.',
    verifiedAt: '2026-09-23',
    source: 'https://www.restaurantji.com/ca/west-point/tacos-estilo-marcos-/',
  },
  {
    id: 'wp_lumberjack_day',
    townId: 'west_point',
    name: 'West Point Lumberjack Day',
    kind: 'show',
    address: 'Main St, West Point',
    phone: '209-293-3100',
    url: 'https://lumberjackday.info/',
    today: 'Saturday Oct 3, 2026: pancake breakfast, soap-box derby, parade at 11, logging show from 1pm. Free.',
    then: 'A celebration of the later timber years, not the Gold Rush.',
    verifiedAt: '2026-09-23',
    source: 'https://lumberjackday.info/',
  },
  {
    id: 'wp_chl268',
    townId: 'west_point',
    name: 'West Point landmark plaque (CHL #268)',
    kind: 'explore',
    address: 'SR 26 at Main St, West Point',
    url: 'https://noehill.com/calaveras/cal0268.asp',
    today: 'Roadside state plaque, always visible.',
    then: 'Camp named Indian Gulch in 1852, West Point in 1854. The Kit Carson naming is the plaque’s tradition, not the record.',
    verifiedAt: '2026-09-23',
    source: 'https://noehill.com/calaveras/cal0268.asp',
  },
  {
    id: 'wp_sandy_gulch',
    townId: 'west_point',
    name: 'Sandy Gulch plaque (CHL #253)',
    kind: 'explore',
    address: 'SR 26, about 1 mile SW of West Point',
    url: 'https://noehill.com/calaveras/cal0253.asp',
    today: 'Roadside plaque — pull fully off SR 26 to read it.',
    then: '1849 trading centre where the Carsner brothers found their nuggets; the district’s first custom stamp mill.',
    verifiedAt: '2026-09-23',
    source: 'https://noehill.com/calaveras/cal0253.asp',
  },
  {
    id: 'mh_leger',
    townId: 'mokelumne_hill',
    name: 'Hotel Léger Restaurant & Bar',
    kind: 'food',
    address: '8304 Main St, Mokelumne Hill',
    phone: '209-286-8004',
    url: 'https://www.hotelleger.com/',
    today: 'Restaurant and saloon in stone rooms; Thu 4–9, Fri–Sat 11–11, Sun 11–4 (own site). Comedy and live music nights.',
    then: 'Part of the building was the Calaveras County Courthouse 1852–1866; George Leger joined it to his hotel (CHL #663).',
    verifiedAt: '2026-09-23',
    source: 'https://www.hotelleger.com/',
  },
  {
    id: 'mh_renegade',
    townId: 'mokelumne_hill',
    name: 'Renegade Winery & Bistro',
    kind: 'food',
    address: '8345 Main St, Mokelumne Hill',
    phone: '209-286-1041',
    url: 'https://www.drinkrenegadewine.com/',
    today: 'Tasting and bistro 11–7; free live music Thursdays 5–7, bands some weekends.',
    then: 'Said to occupy the old Union House (date unverified).',
    verifiedAt: '2026-09-23',
    source: 'https://www.drinkrenegadewine.com/events',
  },
  {
    id: 'mh_moke_a_java',
    townId: 'mokelumne_hill',
    name: 'Moke A Java',
    kind: 'food',
    address: '8320 Main St, Mokelumne Hill',
    url: 'https://www.restaurantji.com/ca/mokelumne-hill/moke-a-java-/',
    today: 'Coffee, pastries, bagel sandwiches; Mon–Wed 7:30–noon, Thu–Sun 7:30–4.',
    then: 'No 1850s building recorded here.',
    verifiedAt: '2026-09-23',
    source: 'https://www.restaurantji.com/ca/mokelumne-hill/moke-a-java-/',
  },
  {
    id: 'mh_history_society',
    townId: 'mokelumne_hill',
    name: 'Mokelumne Hill History Society & Library',
    kind: 'explore',
    address: '8328 Main St, Mokelumne Hill',
    phone: '209-286-0507',
    url: 'https://mokehill.org/',
    today: 'Town archives and Edith Irvine photographs; Tue–Wed 10–5, Thu 1–5, Fri 10–1.',
    then: 'Building date unverified.',
    verifiedAt: '2026-09-23',
    source: 'https://www.gocalaveras.com/business/attractions/mokelumne-hill-history-society/',
  },
  {
    id: 'mh_chinatown_gardens',
    townId: 'mokelumne_hill',
    name: 'Chinatown Gardens (terrace walls)',
    kind: 'explore',
    address: 'E. Center St, two blocks east of Main, Mokelumne Hill',
    url: 'https://mokehill.org/2019/07/take-a-stroll-down-chinatown-gardens/',
    today: 'History Society garden; visitors welcome, no set hours.',
    then: 'Stone terrace walls built by the town’s Chinese residents in the 1800s.',
    verifiedAt: '2026-09-23',
    source: 'https://www.gocalaveras.com/discover-mokelumne-hill/',
  },
  {
    id: 'mh_ioof',
    townId: 'mokelumne_hill',
    name: 'I.O.O.F. Hall (CHL #256)',
    kind: 'explore',
    address: 'Main & Center Sts, Mokelumne Hill',
    url: 'https://noehill.com/calaveras/cal0256.asp',
    today: 'Exterior from the street.',
    then: 'Built 1854 in two stories; the lodge added the third — called the first three-story building in the interior.',
    verifiedAt: '2026-09-23',
    source: 'https://noehill.com/calaveras/cal0256.asp',
  },
  {
    id: 'ac_museum',
    townId: 'angels_camp',
    name: 'Angels Camp Museum',
    kind: 'explore',
    address: '753 S Main St, Angels Camp',
    phone: '209-736-2963',
    url: 'https://www.angelsmuseumfoundation.org/angels-camp-museum.html',
    today: 'Daily 10–4 (last entry 3); $15 adults, $10 ages 6–17; 36 horse-drawn vehicles; gold panning included.',
    then: 'Three acres of the original 1850s Angels Mine claim.',
    verifiedAt: '2026-09-23',
    source: 'https://www.angelsmuseumfoundation.org/angels-camp-museum.html',
  },
  {
    id: 'ac_utica_park',
    townId: 'angels_camp',
    name: 'Utica Park & Mark Twain statue',
    kind: 'explore',
    address: 'S Main St (Hwy 49), Angels Camp',
    url: 'https://www.calaverashistory.org/utica-park-history',
    today: 'Public park, playground, the Twain statue; farmers market Fridays 4:30–7:30 into late September.',
    then: 'Placer-mined from the first Gold Rush days on the Mother Lode vein; the park came much later.',
    verifiedAt: '2026-09-23',
    source: 'https://www.calaverashistory.org/utica-park-history',
  },
  {
    id: 'ac_angels_hotel',
    townId: 'angels_camp',
    name: 'Angels Hotel (landmark exterior)',
    kind: 'explore',
    address: 'S Main St & Bird Way, Angels Camp',
    url: 'https://noehill.com/calaveras/cal0734.asp',
    today: 'View from the street: apartments upstairs, shops below. No bar, no hotel.',
    then: 'C.C. Lake’s canvas hotel of 1851; stone by 1855–57. Twain reportedly heard the frog yarn here from Ben Coon.',
    verifiedAt: '2026-09-23',
    source: 'https://www.calaverasenterprise.com/articles/history/angels-hotel-building-is-rich-in-historical-significance/',
  },
  {
    id: 'ac_angels_creek_cafe',
    townId: 'angels_camp',
    name: 'Angels Creek Café',
    kind: 'food',
    address: '1246 S Main St, Angels Camp',
    phone: '209-736-2941',
    url: 'https://www.restaurantji.com/ca/angels-camp/angels-creek-cafe-/',
    today: 'Breakfast: Mon–Fri 7–1, Sat 7–2 and 5–8, Sun 7–1.',
    then: 'No 1850s building recorded here.',
    verifiedAt: '2026-09-23',
    source: 'https://www.restaurantji.com/ca/angels-camp/angels-creek-cafe-/',
  },
  {
    id: 'ac_cruscos',
    townId: 'angels_camp',
    name: 'Crusco’s',
    kind: 'food',
    address: '1240 S Main St, Angels Camp',
    phone: '209-736-1440',
    url: 'https://www.gocalaveras.com/business/restaurants/cruscos-ristorante-italiano/',
    today: 'Italian; listings disagree on hours — call ahead.',
    then: 'An 1860s warehouse of the Stickle Bros. store.',
    verifiedAt: '2026-09-23',
    source: 'https://www.restaurantji.com/ca/angels-camp/cruscos-/',
  },
  {
    id: 'ac_angels_theatre',
    townId: 'angels_camp',
    name: 'Angels Theatre',
    kind: 'show',
    address: '1228 S Main St, Angels Camp',
    url: 'https://www.cinemaclock.com/movie-theaters/angels-theatre',
    today: 'Movies this week, with recliners.',
    then: 'Art Deco, 1937, on the site of the old Miners Union Hall.',
    verifiedAt: '2026-09-23',
    source: 'https://www.cinemaclock.com/movie-theaters/angels-theatre',
  },
  {
    id: 'ac_frogtown',
    townId: 'angels_camp',
    name: 'Frogtown (Calaveras County Fairgrounds)',
    kind: 'show',
    address: '2465 Gun Club Rd, Angels Camp',
    phone: '209-736-2561',
    url: 'https://www.frogtown.org/',
    today: 'Events only: Oct 24–25 All Hallows Fantasy Faire, Dec 5–6 Spirit of Winter; the Fair & Jumping Frog Jubilee returns May 13–16, 2027.',
    then: 'The frog contest grew from Twain’s 1865 story; the original contest is legend.',
    verifiedAt: '2026-09-23',
    source: 'https://www.frogtown.org/facility-schedule',
  },
  {
    id: 'sa_museum',
    townId: 'san_andreas',
    name: 'Calaveras County Museum (old courthouse & jail)',
    kind: 'explore',
    address: '30 N Main St, San Andreas',
    phone: '209-754-1058',
    url: 'https://www.historicalcalaveras.com/downtown-museum',
    today: 'Daily 10–4; $5 adults, 12 and under free. See the cell that held Black Bart.',
    then: 'Odd Fellows Hall 1856, courthouse and jail 1867. Black Bart pleaded guilty here on Nov 17, 1883.',
    verifiedAt: '2026-09-23',
    source: 'https://www.historicalcalaveras.com/downtown-museum',
  },
  {
    id: 'sa_chl252',
    townId: 'san_andreas',
    name: 'San Andreas plaque (CHL #252) & Main Street',
    kind: 'explore',
    address: 'SR 49 at Main St, San Andreas',
    url: 'https://noehill.com/calaveras/cal0252.asp',
    today: 'Roadside plaque at the head of historic Main Street.',
    then: 'Settled by Mexican miners in 1848; burned 1858 and 1863; county seat from 1866. The Murieta “rendezvous” is legend.',
    verifiedAt: '2026-09-23',
    source: 'https://noehill.com/calaveras/cal0252.asp',
  },
  {
    id: 'sa_gooneys',
    townId: 'san_andreas',
    name: 'Gooney’s Bar & Grill',
    kind: 'food',
    address: '6 Main St, San Andreas',
    phone: '209-754-9115',
    url: 'https://www.gocalaveras.com/business/breweries-beer-saloons/gooneys-bar-grill/',
    today: 'Bar and grill from 4pm; billiards, weekend music. Call ahead.',
    then: 'The old Red Brick Saloon building (date unverified).',
    verifiedAt: '2026-09-23',
    source: 'https://www.restaurantji.com/ca/san-andreas/',
  },
  {
    id: 'sa_pickle_patch',
    townId: 'san_andreas',
    name: 'Pickle Patch',
    kind: 'food',
    address: '577 W Saint Charles St, San Andreas',
    phone: '209-754-1978',
    url: 'https://www.restaurantji.com/ca/san-andreas/pickle-patch-/',
    today: 'Deli with a garden patio, Mon–Fri 10–3.',
    then: 'No 1850s building recorded here.',
    verifiedAt: '2026-09-23',
    source: 'https://www.restaurantji.com/ca/san-andreas/pickle-patch-/',
  },
  {
    id: 'sa_arts_council',
    townId: 'san_andreas',
    name: 'Calaveras County Arts Council Gallery',
    kind: 'show',
    address: '22 N Main St, San Andreas',
    phone: '209-754-1774',
    url: 'https://www.calaverasarts.org/',
    today: 'Gallery Wed–Sat 11–4, rotating shows.',
    then: 'A historic Main Street building (date unverified).',
    verifiedAt: '2026-09-23',
    source: 'https://www.calaverasarts.org/',
  },
]

export const LOCAL_AVOID: LocalAvoid[] = [
  {
    id: 'vol_st_george_dining',
    townId: 'volcano',
    name: 'St. George Hotel restaurant and saloon',
    reason: 'Both listed CLOSED on the hotel’s own site; the office keeps Thu–Sun 4–7pm. Look from the street.',
    verifiedAt: '2026-09-23',
  },
  {
    id: 'vol_coffee',
    townId: 'volcano',
    name: 'Older café listings at 16154 Main',
    reason: 'Aimee’s Coffee Cabin, Legato Coffee Roasters and Kneading Dough are closed — the bakery there now is BAKED. In Amador (Fri–Sun).',
    verifiedAt: '2026-09-23',
  },
  {
    id: 'vol_daffodil_hill',
    townId: 'volcano',
    name: 'Daffodil Hill',
    reason: 'Closed to the public indefinitely since July 2019.',
    verifiedAt: '2026-09-23',
  },
  {
    id: 'wp_getaway_cafe', townId: 'west_point', name: 'Get Away Cafe / Cozy Cabin Cafe (Hwy 26)',
    reason: 'Listed closed (Sep 2026).', verifiedAt: '2026-09-23',
  },
  {
    id: 'mh_petroglyphe', townId: 'mokelumne_hill', name: 'Petroglyphe Gallery',
    reason: 'Retired July 4, 2026.', verifiedAt: '2026-09-23',
  },
  {
    id: 'mh_french_stockton_hills', townId: 'mokelumne_hill', name: 'French Hill and Stockton Hill',
    reason: 'Public access unverified — read the story at the CHL #269 plaque on Main St instead.', verifiedAt: '2026-09-23',
  },
  {
    id: 'ac_sutter_gold_mine', townId: 'angels_camp', name: 'Sutter Gold Mine tours',
    reason: 'Tours ended in 2011, and the mine is near Sutter Creek in Amador County, not Angels Camp.', verifiedAt: '2026-09-23',
  },
  {
    id: 'ac_twain_cabin', townId: 'angels_camp', name: 'Mark Twain Cabin (Jackass Hill)',
    reason: 'A replica in Tuolumne County, not Angels Camp; access unverified.', verifiedAt: '2026-09-23',
  },
  {
    id: 'sa_black_bart_inn', townId: 'san_andreas', name: 'Black Bart Inn restaurant',
    reason: 'Listings disagree on whether it serves food — phone before going.', verifiedAt: '2026-09-23',
  },
]

export function localPlacesFor(townId: string): LocalPlace[] {
  return LOCAL_PLACES.filter((p) => p.townId === townId)
}

export function localAvoidFor(townId: string): LocalAvoid[] {
  return LOCAL_AVOID.filter((a) => a.townId === townId)
}
