var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/adventure/leaderboard/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__5e65ba11._.js")
R.c("server/chunks/ssr/_a3b9117b._.js")
R.c("server/chunks/ssr/_596075eb._.js")
R.c("server/chunks/ssr/[root-of-the-server]__60362835._.js")
R.c("server/chunks/ssr/[root-of-the-server]__d8001078._.js")
R.c("server/chunks/ssr/node_modules_next_dist_982e7503._.js")
R.c("server/chunks/ssr/src_app_5b2047f8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__313a4696._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_next-internal_server_app_adventure_leaderboard_page_actions_7b06c29c.js")
R.m(48913)
module.exports=R.m(48913).exports
