// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/adventure/character/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/adventure/character">> = Specific
  const handler = {} as typeof import("../../src/app/adventure/character/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/adventure/leaderboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/adventure/leaderboard">> = Specific
  const handler = {} as typeof import("../../src/app/adventure/leaderboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/adventure/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/adventure">> = Specific
  const handler = {} as typeof import("../../src/app/adventure/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/adventure/play/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/adventure/play">> = Specific
  const handler = {} as typeof import("../../src/app/adventure/play/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/certificate/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/certificate">> = Specific
  const handler = {} as typeof import("../../src/app/certificate/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/clue/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/clue/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/clue/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/explore/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/explore">> = Specific
  const handler = {} as typeof import("../../src/app/explore/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/game/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/game">> = Specific
  const handler = {} as typeof import("../../src/app/game/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/hub/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hub">> = Specific
  const handler = {} as typeof import("../../src/app/hub/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/leaderboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/leaderboard">> = Specific
  const handler = {} as typeof import("../../src/app/leaderboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/oregon-trail/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/oregon-trail">> = Specific
  const handler = {} as typeof import("../../src/app/oregon-trail/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/rentals/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/rentals">> = Specific
  const handler = {} as typeof import("../../src/app/rentals/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/llm/generate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/llm/generate">> = Specific
  const handler = {} as typeof import("../../src/app/api/llm/generate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/llm/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/llm/health">> = Specific
  const handler = {} as typeof import("../../src/app/api/llm/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
